# Copyright (c) <year> <author> (<email>)
# Distributed under the MIT License.
# See accompanying file LICENSE.md or copy at http://opensource.org/licenses/MIT

language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  global:
    - secure: "gD+vZ7FYKPl9txdOn4QBwU+xGZzUehczAs5M45KqP8IOwOU2v4RDS2b++xqkDtGm1BYmvfM3513sbN4XUZztZ1NElj+wS8mcVjjsnfwxxw50vuFeQoN4RTY078Yv3wIYZ5rq3g74JoSIwMC8WcqRUd4i3ka7OYwAUR88ZEDhjGEyUNFUtXgQV3YUp5B40cG0oS7afGMO2psAa58pZbkRa76PdSYs5xGNG4gh745gJ9KaSj4wDuWM6zCfkE2o//e1BBsRyswjP2jPd0gPxHiIto9kCNgPombwDHHcemaBTVDVKvrsN1P1opvJbXtNZ3B8Wgd7rgAGT6znL1RsWQ9lPY2YnHitQGCn1UCI61qqbqnM1P10vDxd2h4wmQKrvZy4TYXMzjgBF42BVb/dOCGJOOKmKyjYFddnAP6eXvNhcEQvBLI7CuHt7d1JpRWIcSNYfvsm4ehINfjETQWOQtJusZy0kwZEJOorjrg71idNh9HwlVEXgyVuDw4YMsJk8yvrSZ7DF2CQ/LMKQTS/r+/qk7qKLNkpU190A+iLquTJ17VARVQW/CrP+KyIUXP6gTA+LMZKOSmcl4XVZthPpoyD+29vOYoVwXLWy9sFjxDfUVpy82Ws/8+qXh/6n9VLcQ3p0AHY7dtHnKXgU2uXpBN63/sy145DfPfmu3IO8rAV6Oc="
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

matrix:
  exclude:
    - compiler: clang
      env: COVERITY_SCAN_BRANCH_PATTERN=coverity_scan
    - compiler: gcc
      env: COVERITY_SCAN_BRANCH_PATTERN=coverity_scan BUILD_TYPE=Release

addons:
  coverity_scan:
    project:
      name: "imvuong/cppbase"
      description: "Build submitted via Travis CI"
    notification_email: imvuong@gmail.com
    build_command_prepend: "mkdir build; cd build; cmake -DPROJECT_NAME=cppbase -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on .."
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  - bash scripts/install_cmake.sh
  - bash scripts/install_doxygen.sh
  - chmod ugo+x scripts/check_doxygen.sh
  - if [ "$COVERITY_SCAN_BRANCH_PATTERN" != "coverity_scan" ] && [ "$CXX" == "g++" ] && [ "$BUILD_TYPE" == "Debug" ]; then
      pip install --user urllib3[secure];
      pip install --user cpp-coveralls;
    fi

before_script::
  - ls -R $HOME/cmake
  - ls -R $HOME/doxygen

script:
  - if [ "$COVERITY_SCAN_BRANCH_PATTERN" != "coverity_scan" ]; then
      mkdir build;
      cd build;
      $HOME/cmake/bin/cmake -DPROJECT_NAME=cppbase -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on -DDOXYGEN_EXECUTABLE=$HOME/doxygen/bin/doxygen -DBUILD_DOXYGEN_DOCS=on ..;
      make;
      ctest -V;
      ../scripts/check_doxygen.sh;
    fi

after_success:
  - if [ "$COVERITY_SCAN_BRANCH_PATTERN" != "coverity_scan" ] && [ "$CXX" == "g++" ] && [ "$BUILD_TYPE" == "Debug" ]; then
      coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*src/main.cpp.*";
    fi
